# Changes here will be overwritten by Copier
_commit: 3090ee1
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: false
email: bluetooth@koston.org
full_name: J. Nick Koston
github_username: bluetooth-devices
has_cli: false
initial_commit: true
open_source_license: MIT
package_name: xiaogui_ble
project_name: xiaogui-ble
project_short_description: Bluetooth parser for xiaogui scales
project_slug: xiaogui-ble
run_poetry_install: true
setup_github: true
setup_pre_commit: true

